"""Diagnostics plots sub-package.

Re-exports every ``plot_*`` function and the :class:`PlotConfig` dataclass.
The public entry points are :func:`plot` (full report) and
:func:`plot_sweep_comparison` (multi-pattern comparison).
"""

from __future__ import annotations

import os
from typing import Callable, Dict, List, Optional

import matplotlib
import matplotlib.pyplot as plt
import numpy as np

from thalia.diagnostics.diagnostics_report import DiagnosticsReport
from thalia.diagnostics.diagnostics_snapshot import RecorderSnapshot

from ._helpers import PlotConfig
from .firing import (
    plot_correlation_distribution,
    plot_fano_scaling,
    plot_firing_rates,
    plot_isi_distributions,
    plot_population_heatmap,
    plot_spike_raster,
)
from .homeostasis import (
    plot_apical_basal_conductance,
    plot_homeostatic_gains,
    plot_stp_efficacy,
)
from .learning import plot_bcm_thresholds, plot_eligibility_traces, plot_weight_distributions
from .neuromodulators import plot_neuromodulator_conc, plot_neuromodulator_conc_by_region
from .spectral import plot_coherence, plot_region_spectra, plot_spectrograms
from .temporal import (
    plot_effective_synaptic_gain,
    plot_ei_lag,
    plot_ei_phase_portrait,
    plot_voltage_distributions,
    plot_voltage_traces,
)

matplotlib.use("Agg")

__all__ = [
    "PlotConfig",
    "plot",
    "plot_sweep_comparison",
    # firing
    "plot_firing_rates",
    "plot_population_heatmap",
    "plot_isi_distributions",
    "plot_spike_raster",
    "plot_fano_scaling",
    "plot_correlation_distribution",
    # spectral
    "plot_region_spectra",
    "plot_coherence",
    "plot_spectrograms",
    # temporal
    "plot_voltage_traces",
    "plot_ei_phase_portrait",
    "plot_voltage_distributions",
    "plot_ei_lag",
    "plot_effective_synaptic_gain",
    # homeostasis
    "plot_homeostatic_gains",
    "plot_stp_efficacy",
    "plot_apical_basal_conductance",
    # neuromodulators
    "plot_neuromodulator_conc",
    "plot_neuromodulator_conc_by_region",
    # learning
    "plot_weight_distributions",
    "plot_eligibility_traces",
    "plot_bcm_thresholds",
]


# =============================================================================
# PUBLIC ENTRY POINT
# =============================================================================


def plot(
    rec: RecorderSnapshot,
    report: DiagnosticsReport,
    output_dir: str,
    cfg: Optional[PlotConfig] = None,
) -> None:
    """Generate and save diagnostic plots to ``output_dir``.

    Each numbered plot is generated by a dedicated ``plot_*`` function so that
    a failure in one plot never prevents the remaining plots from being saved.
    """
    cfg = cfg or PlotConfig()
    os.makedirs(output_dir, exist_ok=True)
    plot_fns: list[Callable[[RecorderSnapshot, DiagnosticsReport, str, PlotConfig], None]] = [
        plot_firing_rates,
        plot_population_heatmap,
        plot_region_spectra,
        plot_coherence,
        plot_isi_distributions,
        plot_homeostatic_gains,
        plot_stp_efficacy,
        plot_voltage_traces,
        plot_spike_raster,
        plot_ei_phase_portrait,
        plot_spectrograms,
        plot_neuromodulator_conc,
        plot_apical_basal_conductance,
        plot_voltage_distributions,
        plot_neuromodulator_conc_by_region,
        plot_fano_scaling,
        plot_correlation_distribution,
        plot_ei_lag,
        plot_effective_synaptic_gain,
        plot_weight_distributions,
        plot_eligibility_traces,
        plot_bcm_thresholds,
    ]
    failed_plots: list[str] = []
    for fn in plot_fns:
        try:
            fn(rec, report, output_dir, cfg)
        except Exception as exc:  # noqa: BLE001
            failed_plots.append(f"{fn.__name__}: {exc}")
    print(f"\n  All plots saved to: {output_dir}")
    if failed_plots:
        print(f"  WARNING: {len(failed_plots)} plot(s) failed:")
        for msg in failed_plots:
            print(f"    - {msg}")


def plot_sweep_comparison(
    sweep_reports: Dict[str, DiagnosticsReport],
    output_dir: str,
) -> None:
    """Save a multi-panel bar chart comparing key metrics across sweep patterns.

    Panels:

    1. Mean firing rate (Hz) per region+population, grouped by pattern.
    2. E/I ratio per region, grouped by pattern.

    The figure is written to ``<output_dir>/sweep_comparison.png``.
    """
    patterns = list(sweep_reports.keys())
    n_pat = len(patterns)
    colours = matplotlib.colormaps["tab10"].resampled(n_pat)
    pat_colours = {p: colours(i) for i, p in enumerate(patterns)}

    pop_keys: List[str] = sorted(
        {
            pk
            for rep in sweep_reports.values()
            for pk in rep.health.population_status
        }
    )
    region_keys: List[str] = sorted(
        {
            rn
            for rep in sweep_reports.values()
            for rn in rep.regions
        }
    )

    fig, axes = plt.subplots(2, 1, figsize=(max(12, len(pop_keys) * 0.7 + 2), 14))
    fig.suptitle("Sweep Pattern Comparison", fontsize=13)

    # Panel 1: mean FR per population.
    ax0 = axes[0]
    x0 = np.arange(len(pop_keys))
    bar_w = 0.8 / max(n_pat, 1)
    for i, pat in enumerate(patterns):
        rep = sweep_reports[pat]
        heights = []
        for pk in pop_keys:
            rn, pn = pk.split(":", 1)
            fr_val = 0.0
            rs = rep.regions.get(rn)
            if rs is not None:
                pop_s = rs.populations.get(pn)
                if pop_s is not None:
                    fr_val = pop_s.mean_fr_hz if not np.isnan(pop_s.mean_fr_hz) else 0.0
            heights.append(fr_val)
        ax0.bar(x0 + i * bar_w, heights, width=bar_w, label=pat, color=pat_colours[pat], alpha=0.85)
    ax0.set_xticks(x0 + bar_w * (n_pat - 1) / 2)
    ax0.set_xticklabels(pop_keys, rotation=45, ha="right", fontsize=7)
    ax0.set_ylabel("Mean FR (Hz)")
    ax0.set_title("Firing Rates by Population")
    ax0.legend(fontsize=8)

    # Panel 2: E/I ratio per region.
    ax1 = axes[1]
    x1 = np.arange(len(region_keys))
    for i, pat in enumerate(patterns):
        rep = sweep_reports[pat]
        heights = [
            (rep.regions[rn].ei_ratio if rn in rep.regions and not np.isnan(rep.regions[rn].ei_ratio) else 0.0)
            for rn in region_keys
        ]
        ax1.bar(x1 + i * bar_w, heights, width=bar_w, label=pat, color=pat_colours[pat], alpha=0.85)
    ax1.set_xticks(x1 + bar_w * (n_pat - 1) / 2)
    ax1.set_xticklabels(region_keys, rotation=45, ha="right", fontsize=7)
    ax1.set_ylabel("E/I ratio")
    ax1.set_title("E/I Conductance Ratio by Region")
    ax1.legend(fontsize=8)

    fig.tight_layout()
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, "sweep_comparison.png")
    fig.savefig(out_path, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print(f"  \u2713 Sweep comparison figure saved: {out_path}")
