"""
Diagnostics plots — all matplotlib visualisations for a DiagnosticsReport.

The public entry point is :func:`plot`, which dispatches to numbered
``plot_*`` helper functions.  A failure in one plot never prevents the
remaining plots from being saved.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Callable, Dict, List, Optional, Tuple

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import spectrogram as sp_spectrogram

from .diagnostics_types import DiagnosticsReport, PopulationStats, RecorderSnapshot

matplotlib.use("Agg")  # Use non-interactive backend


@dataclass
class PlotConfig:
    """Scale factors for diagnostic figure sizes.

    Pass a customised instance to :func:`plot` to adapt layout for very
    large brains (>100 populations) or custom display environments.
    """

    col_width: float = 4.0           # inches per subplot column
    row_height: float = 3.0          # inches per subplot row (normal panels)
    compact_row_height: float = 2.5  # inches per subplot row (compact panels)
    trace_row_height: float = 1.8    # inches per time-trace row
    height_per_pop: float = 0.2      # inches per population in vertical listings
    timeline_width: float = 14.0     # width (inches) for full-width time-series plots
    timeline_height: float = 5.0     # height (inches) for fixed-height time-series plots
    max_fig_height: float = 40.0     # hard cap on figure height (inches)


def _get_cmap(name: str, n: int | None = None):
    """Return a Matplotlib colormap using the non-deprecated colormaps registry."""
    cmap = matplotlib.colormaps[name]
    return cmap if n is None else cmap.resampled(n)


# =============================================================================
# PUBLIC ENTRY POINT
# =============================================================================


def plot(
    rec: RecorderSnapshot,
    report: DiagnosticsReport,
    output_dir: str,
    cfg: Optional[PlotConfig] = None,
) -> None:
    """Generate and save diagnostic plots to ``output_dir``.

    Requires ``matplotlib``.  Silently skips if it is not installed.
    Each numbered plot is generated by a dedicated ``plot_*`` function so that
    a failure in one plot never prevents the remaining plots from being saved.
    """
    cfg = cfg or PlotConfig()
    os.makedirs(output_dir, exist_ok=True)
    plot_fns: list[Callable[[RecorderSnapshot, DiagnosticsReport, str, PlotConfig], None]] = [
        plot_firing_rates,
        plot_population_heatmap,
        plot_region_spectra,
        plot_coherence,
        plot_isi_distributions,
        plot_homeostatic_gains,
        plot_stp_efficacy,
        plot_voltage_traces,
        plot_spike_raster,
        plot_ei_phase_portrait,
        plot_spectrograms,
        plot_neuromodulator_conc,
        plot_apical_basal_conductance,
        plot_voltage_distributions,
        plot_neuromodulator_conc_by_region,
        plot_fano_scaling,
        plot_correlation_distribution,
        plot_ei_lag,
        plot_effective_synaptic_gain,
    ]
    failed_plots: list[str] = []
    for fn in plot_fns:
        try:
            fn(rec, report, output_dir, cfg)
        except Exception as exc:  # noqa: BLE001
            failed_plots.append(f"{fn.__name__}: {exc}")
    print(f"\n  All plots saved to: {output_dir}")
    if failed_plots:
        print(f"  WARNING: {len(failed_plots)} plot(s) failed:")
        for msg in failed_plots:
            print(f"    - {msg}")


def plot_sweep_comparison(
    sweep_reports: Dict[str, DiagnosticsReport],
    output_dir: str,
) -> None:
    """Save a multi-panel bar chart comparing key metrics across sweep patterns.

    Panels:

    1. Mean firing rate (Hz) per region+population, grouped by pattern.
    2. E/I ratio per region, grouped by pattern.
    3. Stability score per pattern.

    The figure is written to ``<output_dir>/sweep_comparison.png``.
    """
    patterns = list(sweep_reports.keys())
    n_pat = len(patterns)
    colours = matplotlib.colormaps["tab10"].resampled(n_pat)
    pat_colours = {p: colours(i) for i, p in enumerate(patterns)}

    # Collect all (region, population) keys across all reports.
    pop_keys: List[str] = sorted(
        {
            pk
            for rep in sweep_reports.values()
            for pk in rep.health.population_status
        }
    )
    region_keys: List[str] = sorted(
        {
            rn
            for rep in sweep_reports.values()
            for rn in rep.regions
        }
    )

    fig, axes = plt.subplots(3, 1, figsize=(max(12, len(pop_keys) * 0.7 + 2), 14))
    fig.suptitle("Sweep Pattern Comparison", fontsize=13)

    # Panel 1: mean FR per population.
    ax0 = axes[0]
    x0 = np.arange(len(pop_keys))
    bar_w = 0.8 / max(n_pat, 1)
    for i, pat in enumerate(patterns):
        rep = sweep_reports[pat]
        heights = []
        for pk in pop_keys:
            rn, pn = pk.split(":", 1)
            fr_val = 0.0
            rs = rep.regions.get(rn)
            if rs is not None:
                pop_s = rs.populations.get(pn)
                if pop_s is not None:
                    fr_val = pop_s.mean_fr_hz if not np.isnan(pop_s.mean_fr_hz) else 0.0
            heights.append(fr_val)
        ax0.bar(x0 + i * bar_w, heights, width=bar_w, label=pat, color=pat_colours[pat], alpha=0.85)
    ax0.set_xticks(x0 + bar_w * (n_pat - 1) / 2)
    ax0.set_xticklabels(pop_keys, rotation=45, ha="right", fontsize=7)
    ax0.set_ylabel("Mean FR (Hz)")
    ax0.set_title("Firing Rates by Population")
    ax0.legend(fontsize=8)

    # Panel 2: E/I ratio per region.
    ax1 = axes[1]
    x1 = np.arange(len(region_keys))
    for i, pat in enumerate(patterns):
        rep = sweep_reports[pat]
        heights = [
            (rep.regions[rn].ei_ratio if rn in rep.regions and not np.isnan(rep.regions[rn].ei_ratio) else 0.0)
            for rn in region_keys
        ]
        ax1.bar(x1 + i * bar_w, heights, width=bar_w, label=pat, color=pat_colours[pat], alpha=0.85)
    ax1.set_xticks(x1 + bar_w * (n_pat - 1) / 2)
    ax1.set_xticklabels(region_keys, rotation=45, ha="right", fontsize=7)
    ax1.set_ylabel("E/I ratio")
    ax1.set_title("E/I Conductance Ratio by Region")
    ax1.legend(fontsize=8)

    # Panel 3: stability score per pattern.
    ax2 = axes[2]
    scores = [sweep_reports[p].health.stability_score for p in patterns]
    bar_colours = [pat_colours[p] for p in patterns]
    ax2.bar(patterns, scores, color=bar_colours, alpha=0.85)
    ax2.set_ylim(0, 1.05)
    ax2.set_ylabel("Stability score")
    ax2.set_title("Overall Stability Score by Pattern")
    ax2.axhline(0.7, color="orange", linestyle="--", linewidth=0.8, label="OK threshold (0.7)")
    ax2.legend(fontsize=8)

    fig.tight_layout()
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, "sweep_comparison.png")
    fig.savefig(out_path, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print(f"  ✓ Sweep comparison figure saved: {out_path}")


# =============================================================================
# COLOUR HELPER
# =============================================================================


def _pop_color(ps: PopulationStats) -> str:
    """Return a hex colour string summarising a population's health."""
    if ps.total_spikes == 0:
        return "#e74c3c"
    if ps.bio_plausibility == "ok":
        return "#2ecc71"
    if ps.bio_plausibility in ("low", "high"):
        return "#f39c12"
    return "#95a5a6"


def _unhealthiness(ps: PopulationStats) -> float:
    """Score how unhealthy a population is (higher = worse).

    Used to prioritize which populations appear in detail plots.
    Scoring:
    - OOB firing rate: distance from bio range, normalised by range midpoint
    - High pairwise correlation (synchrony pathology)
    - High burst fraction (epileptiform)
    - Silent populations get a fixed high score
    - In-range populations score ~0
    """
    score = 0.0

    # Firing rate distance from bio range
    if ps.bio_range_hz is not None:
        lo, hi = ps.bio_range_hz
        mid = (lo + hi) / 2.0 if (lo + hi) > 0 else 1.0
        if ps.mean_fr_hz < lo:
            score += (lo - ps.mean_fr_hz) / mid
        elif ps.mean_fr_hz > hi:
            score += (ps.mean_fr_hz - hi) / mid

    # Silent population
    if ps.total_spikes == 0:
        score += 5.0

    # Synchrony pathology
    if not np.isnan(ps.pairwise_correlation) and ps.pairwise_correlation > 0.15:
        score += ps.pairwise_correlation * 3.0

    # Epileptiform bursting
    if ps.fraction_burst_events > 0.03:
        score += ps.fraction_burst_events * 10.0

    # High SFA index (runaway adaptation)
    if not np.isnan(ps.sfa_index) and ps.sfa_index > 3.0:
        score += (ps.sfa_index - 3.0)

    return score


def _rank_populations_by_health(report: DiagnosticsReport) -> List[Tuple[str, str]]:
    """Return all (region_name, pop_name) pairs sorted by unhealthiness descending.

    Unhealthy populations come first; ties broken by total spikes (more active first).
    """
    items: List[Tuple[float, int, str, str]] = []
    for rs in report.regions.values():
        for ps in rs.populations.values():
            items.append((-_unhealthiness(ps), -ps.total_spikes, ps.region_name, ps.population_name))
    items.sort()
    return [(rn, pn) for _, _, rn, pn in items]


def _rank_regions_by_health(report: DiagnosticsReport) -> List[str]:
    """Return region names sorted by worst population unhealthiness descending."""
    region_scores: Dict[str, float] = {}
    for rs in report.regions.values():
        worst = max((_unhealthiness(ps) for ps in rs.populations.values()), default=0.0)
        region_scores[rs.region_name] = worst
    return sorted(region_scores, key=lambda rn: (-region_scores[rn], rn))


# =============================================================================
# INDIVIDUAL PLOTS
# =============================================================================


def plot_firing_rates(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Horizontal bar chart of mean firing rates per population."""
    fig, ax = plt.subplots(figsize=(cfg.timeline_width, min(cfg.max_fig_height, max(6, rec._n_pops * cfg.height_per_pop))))
    labels, values, colors = [], [], []
    for rn, rs in report.regions.items():
        for pn, ps in rs.populations.items():
            labels.append(f"{rn}:{pn}")
            values.append(ps.mean_fr_hz)
            colors.append(_pop_color(ps))
    y_pos = np.arange(len(labels))
    ax.barh(y_pos, values, color=colors, height=0.8)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=6)
    ax.set_xlabel("Firing rate (Hz)")
    ax.set_title("Population Firing Rates  (green=bio-ok, orange=out-of-range, red=silent)")
    ax.axvline(0, color="k", linewidth=0.5)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "01_firing_rates.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 01_firing_rates.png")


def plot_population_heatmap(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Population firing-rate heatmap over time."""
    if report.pop_rate_binned is None:
        return
    pop_keys = rec._pop_keys
    pr = report.pop_rate_binned  # [n_bins, n_pops]
    pr_hz = pr * (1000.0 / rec.config.rate_bin_ms)
    t_axis = np.arange(pr_hz.shape[0]) * rec.config.rate_bin_ms
    fig, ax = plt.subplots(figsize=(cfg.timeline_width + 2, min(cfg.max_fig_height, max(6, rec._n_pops * cfg.height_per_pop * 0.9))))
    vmax = float(np.percentile(pr_hz, 99)) or 1.0
    im = ax.imshow(
        pr_hz.T,
        aspect="auto",
        origin="lower",
        interpolation="none",
        extent=[t_axis[0], t_axis[-1], 0, rec._n_pops],
        cmap="hot",
        vmin=0,
        vmax=vmax,
    )
    ax.set_yticks(np.arange(rec._n_pops) + 0.5)
    ax.set_yticklabels([f"{rn}:{pn}" for rn, pn in pop_keys], fontsize=5)
    ax.set_xlabel("Time (ms)")
    ax.set_title("Population Firing Rate Heatmap (Hz)")
    plt.colorbar(im, ax=ax, label="Firing rate (Hz)")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "02_population_heatmap.png"), dpi=120)
    plt.close(fig)
    print(f"  ✓ 02_population_heatmap.png")


def plot_region_spectra(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Per-region normalised band-power bar charts."""
    osc = report.oscillations
    n_plots = len(report.region_keys or [])
    if n_plots == 0:
        return
    ncols = 4
    nrows = (n_plots + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * cfg.col_width, nrows * cfg.compact_row_height))
    axes = np.array(axes).flatten()
    colors_bar = ["#3498db", "#2ecc71", "#f39c12", "#e74c3c", "#9b59b6"]
    for ax_i, rn in enumerate(report.region_keys or []):
        ax = axes[ax_i]
        bp = osc.region_band_power.get(rn, {})
        bands = list(bp.keys())
        powers = [bp[b] for b in bands]
        ax.bar(bands, powers, color=colors_bar[: len(bands)])
        ax.set_title(rn, fontsize=7, pad=2)
        ax.set_ylim(0, 1)
        ax.tick_params(labelsize=6)
        dom_freq = osc.region_dominant_freq.get(rn, 0.0)
        if dom_freq > 0:
            ax.text(0.98, 0.95, f"{dom_freq:.1f} Hz", ha="right", va="top",
                    transform=ax.transAxes, fontsize=7)
    for ax_i in range(n_plots, len(axes)):
        axes[ax_i].set_visible(False)
    fig.suptitle("Per-Region Power Spectra", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "03_region_spectra.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 03_region_spectra.png")


def plot_coherence(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Cross-regional coherence matrices (theta, beta, gamma)."""
    osc = report.oscillations
    n_r = len(osc.region_order)
    for band_label, coh_mat, fname in [
        ("Theta (4–8 Hz)",   osc.coherence_theta, "04_coherence_theta.png"),
        ("Beta (13–30 Hz)",  osc.coherence_beta,  "04b_coherence_beta.png"),
        ("Gamma (30–100 Hz)", osc.coherence_gamma, "04c_coherence_gamma.png"),
    ]:
        fig, ax = plt.subplots(figsize=(max(8, n_r * 0.5), min(cfg.max_fig_height, max(6, n_r * 0.5))))
        cmap = plt.cm.YlOrRd.copy()  # type: ignore[attr-defined]
        cmap.set_bad(color="lightgrey")  # NaN = unsampled pair → grey
        im = ax.imshow(coh_mat, vmin=0, vmax=1, cmap=cmap, aspect="equal")
        ax.set_xticks(np.arange(n_r))
        ax.set_xticklabels(osc.region_order, rotation=90, fontsize=6)
        ax.set_yticks(np.arange(n_r))
        ax.set_yticklabels(osc.region_order, fontsize=6)
        ax.set_title(f"Cross-Regional Coherence — {band_label}")
        plt.colorbar(im, ax=ax, label="Coherence")
        plt.tight_layout()
        fig.savefig(os.path.join(output_dir, fname), dpi=150)
        plt.close(fig)
        print(f"  ✓ {fname}")


def plot_isi_distributions(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """ISI histograms for a selection of key populations."""
    # Prioritise unhealthy populations; only include those with spike time data.
    ranked = _rank_populations_by_health(report)
    key_pops = [(rn, pn) for rn, pn in ranked if (rn, pn) in rec._spike_times][:12]
    if not key_pops:
        return
    ncols = min(4, len(key_pops))
    nrows = (len(key_pops) + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * cfg.col_width, nrows * cfg.row_height))
    axes = np.array(axes).flatten()
    for ax_i, key in enumerate(key_pops):
        ax = axes[ax_i]
        all_isis: List[float] = []
        for times in rec._spike_times[key]:
            if len(times) >= 2:
                all_isis.extend(np.diff(times))
        if all_isis:
            isis_ms = np.array(all_isis, dtype=np.float32) * rec.dt_ms
            ax.hist(
                isis_ms, bins=50, range=(0, float(np.percentile(isis_ms, 98))),
                color="#3498db", edgecolor="none", density=True
            )
            cv = np.std(isis_ms) / np.mean(isis_ms) if np.mean(isis_ms) > 0 else 0
            ax.set_title(f"{key[0]}:{key[1]}\nCV={cv:.2f}", fontsize=7)
            ax.set_xlabel("ISI (ms)", fontsize=7)
            ax.tick_params(labelsize=6)
    for ax_i in range(len(key_pops), len(axes)):
        axes[ax_i].set_visible(False)
    fig.suptitle("Inter-Spike Interval Distributions", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "05_isi_distributions.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 05_isi_distributions.png")


def plot_homeostatic_gains(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Homeostatic gain trajectories over time."""
    hs = report.homeostasis
    if not hs.gain_trajectories or len(hs.gain_sample_times_ms) <= 1:
        return
    t_ms = hs.gain_sample_times_ms
    fig, ax = plt.subplots(figsize=(cfg.timeline_width, cfg.timeline_height))
    cmap = _get_cmap("tab20")
    for i, (key, traj) in enumerate(sorted(hs.gain_trajectories.items())):
        valid = ~np.isnan(traj)
        if valid.sum() < 2:
            continue
        ax.plot(t_ms[valid], traj[valid], linewidth=0.8, alpha=0.7,
                color=cmap(i % 20), label=key)
    ax.axhline(0.3, color="red", linestyle="--", linewidth=1.0, label="Collapse threshold")
    ax.axhline(1.0, color="gray", linestyle=":", linewidth=0.8)
    ax.set_xlabel("Time (ms)")
    ax.set_ylabel("g_L_scale")
    ax.set_title("Homeostatic Gain Trajectories")
    ax.set_ylim(0, 2.1)
    ax.legend(fontsize=5, ncol=3, loc="upper right")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "06_homeostatic_gains.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 06_homeostatic_gains.png")


def plot_stp_efficacy(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """STP efficacy (x·u) trajectories per synapse over time."""
    hs_stp = report.homeostasis.stp_efficacy_history
    if not hs_stp or len(report.homeostasis.gain_sample_times_ms) <= 1:
        return
    t_ms = report.homeostasis.gain_sample_times_ms
    fig, ax = plt.subplots(figsize=(cfg.timeline_width, cfg.timeline_height))
    cmap_stp = _get_cmap("tab20")
    for i, (key, traj) in enumerate(sorted(hs_stp.items())):
        valid = ~np.isnan(traj)
        if valid.sum() < 2:
            continue
        ax.plot(t_ms[valid], traj[valid], linewidth=0.8, alpha=0.7,
                color=cmap_stp(i % 20), label=key)
    ax.axhline(0.0, color="gray", linestyle=":", linewidth=0.8)
    ax.set_xlabel("Time (ms)")
    ax.set_ylabel("STP efficacy (x·u)")
    ax.set_title("STP Efficacy Trajectories (per synapse)")
    ax.set_ylim(-0.05, 1.05)
    ax.legend(fontsize=5, ncol=3, loc="upper right")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "06b_stp_efficacy.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 06b_stp_efficacy.png")


def plot_voltage_traces(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Sample neuron voltage traces for key populations."""
    if report.raw_voltages is None:
        return

    # Prioritise unhealthy populations; only include those with voltage data.
    ranked = _rank_populations_by_health(report)
    sampled: List[Tuple[str, str, int]] = []
    for rn, pn in ranked:
        if len(sampled) >= 6:
            break
        if (rn, pn) not in rec._pop_index:
            continue
        idx = rec._pop_index[(rn, pn)]
        if not np.all(np.isnan(report.raw_voltages[:, idx, :])):
            sampled.append((rn, pn, idx))
    if not sampled:
        return
    fig, axes = plt.subplots(len(sampled), 1, figsize=(cfg.timeline_width + 2, min(cfg.max_fig_height, len(sampled) * cfg.trace_row_height)), sharex=True)
    if len(sampled) == 1:
        axes = [axes]
    t_ms = np.arange(report.n_timesteps, dtype=np.float32) * rec.dt_ms
    for ax, (rn, pn, pidx) in zip(axes, sampled):
        v = report.raw_voltages[:, pidx, :]  # [T, sample_size]
        n_valid = int(rec._pop_sizes[pidx])
        n_show = min(8, n_valid, v.shape[1])
        for ni in range(n_show):
            col = _get_cmap("tab10")(ni)
            y = v[:, ni]
            valid_mask = ~np.isnan(y)
            if valid_mask.sum() > 1:
                ax.plot(t_ms[valid_mask], y[valid_mask], linewidth=0.5, alpha=0.7, color=col)
        ax.set_ylabel(f"{pn}\n({rn})", fontsize=6)
        ax.tick_params(labelsize=6)
    axes[-1].set_xlabel("Time (ms)")
    fig.suptitle("Sample Neuron Voltage Traces", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "07_voltage_traces.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 07_voltage_traces.png")


def plot_spike_raster(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Spike raster plots for key regions."""
    if not rec._spike_times:
        return
    # Prioritise regions with the unhealthiest populations.
    ranked_regions = _rank_regions_by_health(report)
    existing = [rn for rn in ranked_regions if rn in rec._region_pop_indices][:6]
    if not existing:
        return
    fig, axes = plt.subplots(
        len(existing), 1,
        figsize=(cfg.timeline_width + 2, min(cfg.max_fig_height, len(existing) * cfg.compact_row_height)),
        sharex=True,
    )
    if len(existing) == 1:
        axes = [axes]
    t_ms_max = report.n_timesteps * rec.dt_ms
    for ax, rn in zip(axes, existing):
        y_offset = 0
        pop_names = [rec._pop_keys[i][1] for i in rec._region_pop_indices[rn]]
        pop_colors_raster = _get_cmap("tab10")
        for pi, pn in enumerate(pop_names):
            key = (rn, pn)
            if key not in rec._spike_times:
                continue
            n_neurons = len(rec._spike_times[key])
            n_show = min(80, n_neurons)
            col = pop_colors_raster(pi % 10)
            for ni in range(n_show):
                times = rec._spike_times[key][ni]
                if times:
                    t_vals = np.array(times, dtype=np.float32) * rec.dt_ms
                    ax.scatter(
                        t_vals, np.full_like(t_vals, y_offset + ni),
                        s=1.0, c=[col], marker="|", linewidths=0.5
                    )
            ax.axhline(y_offset + n_show, color="gray", linewidth=0.3)
            ax.text(
                t_ms_max * 1.002, y_offset + n_show / 2, pn,
                fontsize=6, va="center"
            )
            y_offset += n_show + 5
        ax.set_ylabel(rn, fontsize=8)
        ax.set_xlim(0, t_ms_max)
        ax.tick_params(labelsize=6)
    axes[-1].set_xlabel("Time (ms)")
    fig.suptitle("Spike Rasters (sample neurons)", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "08_raster_plots.png"), dpi=130)
    plt.close(fig)
    print(f"  ✓ 08_raster_plots.png")


def plot_ei_phase_portrait(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """E/I conductance phase portraits for key populations."""
    if (
        rec._g_exc_samples is None
        or rec._g_inh_samples is None
    ):
        return
    if np.all(np.isnan(rec._g_exc_samples)) or np.all(np.isnan(rec._g_inh_samples)):
        return
    pop_keys = rec._pop_keys
    key_ei_pops = ["relay", "ca1", "l23_pyr", "l4_pyr"]
    sampled_ei: List[Tuple[str, str, int]] = []
    for rn, pn in pop_keys:
        if any(t in pn for t in key_ei_pops) and len(sampled_ei) < 6:
            idx = rec._pop_index[(rn, pn)]
            sampled_ei.append((rn, pn, idx))
    if not sampled_ei:
        return
    fig, axes = plt.subplots(
        1, len(sampled_ei),
        figsize=(len(sampled_ei) * cfg.row_height, cfg.row_height),
    )
    if len(sampled_ei) == 1:
        axes = [axes]
    n_cond = rec._cond_sample_step
    for ax, (rn, pn, pidx) in zip(axes, sampled_ei):
        g_e = rec._g_exc_samples[:n_cond, pidx, :].flatten()
        g_i = rec._g_inh_samples[:n_cond, pidx, :].flatten()
        valid = ~(np.isnan(g_e) | np.isnan(g_i))
        if valid.sum() > 5:
            ax.scatter(g_e[valid], g_i[valid], s=2, alpha=0.4, c="#3498db")
        ax.set_xlabel("g_exc", fontsize=7)
        ax.set_ylabel("g_inh", fontsize=7)
        ax.set_title(f"{pn}\n({rn})", fontsize=7)
        ax.tick_params(labelsize=6)
    fig.suptitle("E/I Conductance Phase Portraits", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "09_ei_phase_portrait.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 09_ei_phase_portrait.png")


def plot_spectrograms(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Time-frequency spectrograms of population rates per region."""
    n_steps = rec._n_recorded or rec.config.n_timesteps
    if n_steps <= 0 or rec._n_regions <= 0:
        return
    bin_steps = max(1, int(rec.config.rate_bin_ms / rec.dt_ms))
    n_bins = n_steps // bin_steps
    fs_bins = 1000.0 / rec.config.rate_bin_ms

    # Consume the pre-normalised region-rate matrix from the report (avoids
    # recomputing it with different normalisation from rec._region_spike_counts).
    if report.region_rate_binned is not None and report.region_rate_binned.shape == (n_bins, rec._n_regions):
        region_rate_binned = report.region_rate_binned
    else:
        # Fallback: recompute without population-size normalisation.
        region_rate_binned = np.zeros((n_bins, rec._n_regions), dtype=np.float32)
        for b in range(n_bins):
            start, end = b * bin_steps, (b + 1) * bin_steps
            region_rate_binned[b] = rec._region_spike_counts[start:end].sum(axis=0)

    n_col = min(4, rec._n_regions)
    n_row = (rec._n_regions + n_col - 1) // n_col
    fig_sg, axes_sg = plt.subplots(
        n_row, n_col,
        figsize=(n_col * cfg.col_width, n_row * cfg.row_height),
        squeeze=False,
        sharex=True,
    )
    nperseg_sg = min(n_bins, 128)
    for r_idx, rn in enumerate(rec._region_keys):
        ax = axes_sg[r_idx // n_col][r_idx % n_col]
        trace = region_rate_binned[:, r_idx].astype(float)
        if trace.std() > 0 and nperseg_sg >= 8:
            f_sg, t_sg, Sxx = sp_spectrogram(
                trace, fs=fs_bins, nperseg=nperseg_sg,
                noverlap=nperseg_sg // 2, window="hann", scaling="density"
            )
            f_mask = f_sg <= 100.0
            ax.pcolormesh(
                t_sg, f_sg[f_mask], 10 * np.log10(Sxx[f_mask] + 1e-12),
                shading="gouraud", cmap="magma",
            )
        ax.set_title(rn, fontsize=7)
        ax.set_ylabel("Freq (Hz)", fontsize=6)
        ax.tick_params(labelsize=5)
    for r_idx in range(rec._n_regions, n_row * n_col):
        axes_sg[r_idx // n_col][r_idx % n_col].set_visible(False)
    fig_sg.supxlabel("Time (s)", fontsize=8)
    fig_sg.suptitle("Population Rate Spectrograms", fontsize=10)
    plt.tight_layout()
    fig_sg.savefig(os.path.join(output_dir, "10_spectrograms.png"), dpi=130)
    plt.close(fig_sg)
    print(f"  ✓ 10_spectrograms.png")


def plot_neuromodulator_conc(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Neuromodulator receptor concentration trajectories over time."""
    if not report.neuromodulator_levels:
        return
    t_ms = report.homeostasis.gain_sample_times_ms
    nm_levels = report.neuromodulator_levels
    n_receptors = len(nm_levels)
    n_col_nm = min(4, n_receptors)
    n_row_nm = (n_receptors + n_col_nm - 1) // n_col_nm
    fig_nm, axes_nm = plt.subplots(
        n_row_nm, n_col_nm,
        figsize=(n_col_nm * cfg.col_width, n_row_nm * cfg.compact_row_height),
        squeeze=False,
        sharex=True,
    )
    for nm_i, (key, traj) in enumerate(sorted(nm_levels.items())):
        ax = axes_nm[nm_i // n_col_nm][nm_i % n_col_nm]
        valid = ~np.isnan(traj)
        if valid.sum() > 1 and len(t_ms) >= valid.sum():
            ax.plot(t_ms[:valid.sum()], traj[valid], linewidth=1.0, color="#9b59b6")
        ax.set_title(key, fontsize=6)
        ax.set_ylabel("Concentration", fontsize=6)
        ax.set_ylim(-0.02, 1.05)
        ax.axhline(0, color="gray", linewidth=0.5, linestyle=":")
        ax.tick_params(labelsize=5)
    for nm_i in range(n_receptors, n_row_nm * n_col_nm):
        axes_nm[nm_i // n_col_nm][nm_i % n_col_nm].set_visible(False)
    fig_nm.supxlabel("Time (ms)", fontsize=8)
    fig_nm.suptitle("Neuromodulator Receptor Concentrations", fontsize=10)
    plt.tight_layout()
    fig_nm.savefig(os.path.join(output_dir, "11_neuromodulator_conc.png"), dpi=150)
    plt.close(fig_nm)
    print(f"  ✓ 11_neuromodulator_conc.png")


def plot_apical_basal_conductance(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Apical vs. basal AMPA conductance per population (TwoCompartmentLIF only)."""
    if (
        rec._g_apical_samples is None
        or rec._g_exc_samples is None
        or rec._cond_sample_step == 0
    ):
        return
    n_cond = rec._cond_sample_step

    labels: List[str] = []
    basal_means: List[float] = []
    apical_means: List[float] = []
    for pidx, (rn, pn) in enumerate(rec._pop_keys):
        apical_slab = rec._g_apical_samples[:n_cond, pidx, :]
        apical_mean = float(np.nanmean(apical_slab))
        if np.isnan(apical_mean):
            continue
        basal_slab = rec._g_exc_samples[:n_cond, pidx, :]
        basal_mean = float(np.nanmean(basal_slab))
        if np.isnan(basal_mean):
            basal_mean = 0.0
        labels.append(f"{pn}\n({rn})")
        basal_means.append(basal_mean)
        apical_means.append(apical_mean)

    if not labels:
        return

    n = len(labels)
    y = np.arange(n)
    bar_h = 0.35
    fig, ax = plt.subplots(figsize=(10, min(cfg.max_fig_height, max(4, n * 0.55))))
    ax.barh(y - bar_h / 2, basal_means, bar_h, label="Basal (g_exc AMPA)", color="#3498db", alpha=0.85)
    ax.barh(y + bar_h / 2, apical_means, bar_h, label="Apical (g_exc_apical)", color="#e67e22", alpha=0.85)
    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=7)
    ax.set_xlabel("Mean conductance")
    ax.set_title("Apical vs. Basal AMPA Conductance per Population")
    ax.legend(fontsize=8)
    ax.axvline(0, color="black", linewidth=0.5)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "12_apical_basal_conductance.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 12_apical_basal_conductance.png")


def plot_voltage_distributions(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Per-population voltage distributions as violin plots."""
    if report.raw_voltages is None:
        return

    pops_with_data: List[Tuple[str, str, int]] = []
    for pidx, (rn, pn) in enumerate(rec._pop_keys):
        if not np.all(np.isnan(report.raw_voltages[:, pidx, :])):
            pops_with_data.append((rn, pn, pidx))

    if not pops_with_data:
        return

    n = len(pops_with_data)
    n_col = min(4, n)
    n_row = (n + n_col - 1) // n_col
    fig, axes = plt.subplots(n_row, n_col, figsize=(n_col * cfg.col_width, n_row * cfg.row_height), squeeze=False)

    for i, (rn, pn, pidx) in enumerate(pops_with_data):
        ax = axes[i // n_col][i % n_col]
        v_flat = report.raw_voltages[:, pidx, :].flatten()
        v_flat = v_flat[~np.isnan(v_flat)]
        if len(v_flat) < 10:
            ax.set_visible(False)
            continue
        vp = ax.violinplot(v_flat, showmedians=True, showextrema=False)
        for body in vp.get("bodies", []):
            body.set_facecolor("#3498db")
            body.set_alpha(0.7)
        rs = report.regions.get(rn)
        pop_stats = rs.populations.get(pn) if rs else None
        bc = (
            pop_stats.voltage_bimodality
            if pop_stats is not None and not np.isnan(pop_stats.voltage_bimodality)
            else None
        )
        subtitle = f"({rn})"
        if bc is not None:
            subtitle += f"  BC={bc:.3f}"
        ax.set_title(f"{pn}\n{subtitle}", fontsize=6)
        ax.set_xticks([])
        ax.set_ylabel("Voltage (mV)", fontsize=6)
        ax.tick_params(labelsize=6)

    for i in range(len(pops_with_data), n_row * n_col):
        axes[i // n_col][i % n_col].set_visible(False)

    fig.suptitle("Population Voltage Distributions", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "13_voltage_distributions.png"), dpi=130)
    plt.close(fig)
    print(f"  ✓ 13_voltage_distributions.png")


def plot_neuromodulator_conc_by_region(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Neuromodulator receptor concentrations grouped by brain region."""
    if not report.neuromodulator_levels:
        return
    t_ms = report.homeostasis.gain_sample_times_ms
    nm_levels = report.neuromodulator_levels  # keys: "{region}/{mod_name}"

    by_region: Dict[str, List[Tuple[str, np.ndarray]]] = {}
    for key in sorted(nm_levels.keys()):
        rn, mod_name = key.split("/", 1)
        if rn not in by_region:
            by_region[rn] = []
        by_region[rn].append((mod_name, nm_levels[key]))

    if not by_region:
        return

    n_regions = len(by_region)
    n_col = min(3, n_regions)
    n_row = (n_regions + n_col - 1) // n_col
    fig, axes = plt.subplots(
        n_row, n_col,
        figsize=(n_col * (cfg.col_width + 1.0), n_row * cfg.row_height),
        squeeze=False,
        sharex=True,
    )
    colors = [_get_cmap("tab10")(i) for i in range(10)]

    for r_i, (rn, mod_list) in enumerate(sorted(by_region.items())):
        ax = axes[r_i // n_col][r_i % n_col]
        for m_i, (mod_name, traj) in enumerate(mod_list):
            valid = ~np.isnan(traj)
            if valid.sum() > 1 and len(t_ms) >= valid.sum():
                ax.plot(
                    t_ms[: valid.sum()], traj[valid],
                    linewidth=1.2, color=colors[m_i % 10], label=mod_name,
                )
        ax.set_title(rn, fontsize=8)
        ax.set_ylabel("Concentration", fontsize=6)
        ax.set_ylim(-0.02, 1.05)
        ax.axhline(0, color="gray", linewidth=0.5, linestyle=":")
        ax.legend(fontsize=5, loc="upper right")
        ax.tick_params(labelsize=5)

    for r_i in range(n_regions, n_row * n_col):
        axes[r_i // n_col][r_i % n_col].set_visible(False)

    fig.supxlabel("Time (ms)", fontsize=8)
    fig.suptitle("Neuromodulator Concentrations by Region", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "14_neuromodulator_conc_by_region.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 14_neuromodulator_conc_by_region.png")


def plot_fano_scaling(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Fano factor vs bin width for top populations.

    A Poisson process yields FF=1 at all time scales (shown as dashed reference).
    Bursty or correlated activity shows FF increasing with bin width.
    """
    # Collect populations with non-empty fano_scaling
    entries: list[tuple[str, str, list[tuple[float, float]]]] = []
    for rs in report.regions.values():
        for ps in rs.populations.values():
            if ps.fano_scaling:
                entries.append((ps.region_name, ps.population_name, ps.fano_scaling))

    if not entries:
        return

    # Prioritise unhealthy populations, show top 12
    entries.sort(
        key=lambda e: (-_unhealthiness(report.regions[e[0]].populations[e[1]]),
                       -report.regions[e[0]].populations[e[1]].total_spikes),
    )
    entries = entries[:12]

    n_cols = min(4, len(entries))
    n_rows = (len(entries) + n_cols - 1) // n_cols
    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(cfg.col_width * n_cols, cfg.row_height * n_rows),
        squeeze=False,
    )
    for i, (rn, pn, scaling) in enumerate(entries):
        ax = axes[i // n_cols][i % n_cols]
        bin_widths = [s[0] for s in scaling]
        ff_values = [s[1] for s in scaling]
        ax.plot(bin_widths, ff_values, "o-", markersize=4, linewidth=1.5)
        ax.axhline(1.0, color="gray", linestyle="--", linewidth=0.8, label="Poisson")
        ax.set_xscale("log")
        ax.set_xlabel("Bin width (ms)", fontsize=7)
        ax.set_ylabel("Fano factor", fontsize=7)
        ax.set_title(f"{rn}:{pn}", fontsize=7)
        ax.tick_params(labelsize=6)
        ax.legend(fontsize=5)

    for i in range(len(entries), n_rows * n_cols):
        axes[i // n_cols][i % n_cols].set_visible(False)

    fig.suptitle("Fano Factor Scaling (FF vs Bin Width)", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "15_fano_scaling.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 15_fano_scaling.png")


def plot_correlation_distribution(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Histogram of pairwise correlation coefficients.

    A healthy AI-state network should show a distribution peaked near zero.
    Epileptiform activity shifts the distribution toward positive values.
    """
    # Collect populations with non-empty distributions
    entries: list[tuple[str, str, np.ndarray]] = []
    for rs in report.regions.values():
        for ps in rs.populations.values():
            if ps.pairwise_correlation_distribution is not None and len(ps.pairwise_correlation_distribution) > 0:
                entries.append((ps.region_name, ps.population_name, ps.pairwise_correlation_distribution))

    if not entries:
        return

    # Prioritise unhealthy populations, show top 12
    entries.sort(
        key=lambda e: (-_unhealthiness(report.regions[e[0]].populations[e[1]]),
                       -report.regions[e[0]].populations[e[1]].total_spikes),
    )
    entries = entries[:12]

    n_cols = min(4, len(entries))
    n_rows = (len(entries) + n_cols - 1) // n_cols
    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(cfg.col_width * n_cols, cfg.row_height * n_rows),
        squeeze=False,
    )
    for i, (rn, pn, r_values) in enumerate(entries):
        ax = axes[i // n_cols][i % n_cols]
        ax.hist(r_values, bins=30, range=(-1.0, 1.0), color="steelblue", edgecolor="black", linewidth=0.3)
        ax.axvline(0.0, color="gray", linestyle="--", linewidth=0.8)
        mean_r = float(np.mean(r_values))
        ax.axvline(mean_r, color="red", linestyle="-", linewidth=1.0, label=f"mean={mean_r:.3f}")
        ax.set_xlabel("Pearson r", fontsize=7)
        ax.set_ylabel("Count", fontsize=7)
        ax.set_title(f"{rn}:{pn}", fontsize=7)
        ax.tick_params(labelsize=6)
        ax.legend(fontsize=5)

    for i in range(len(entries), n_rows * n_cols):
        axes[i // n_cols][i % n_cols].set_visible(False)

    fig.suptitle("Pairwise Correlation Distribution", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "16_correlation_distribution.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 16_correlation_distribution.png")


def plot_ei_lag(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """E/I conductance lag per region as a bar chart.

    Shows the lag in ms at which the cross-correlation between excitatory and
    inhibitory conductance peaks, along with the peak correlation value.
    """
    # Collect regions with valid E/I lag data
    regions: list[tuple[str, float, float]] = []
    for rn, rs in report.regions.items():
        if not np.isnan(rs.ei_lag_ms) and not np.isnan(rs.ei_xcorr_peak):
            regions.append((rn, rs.ei_lag_ms, rs.ei_xcorr_peak))

    if not regions:
        return

    regions.sort(key=lambda x: x[0])
    names = [r[0] for r in regions]
    lags = [r[1] for r in regions]
    xcorrs = [r[2] for r in regions]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(cfg.timeline_width, cfg.timeline_height))

    # Left panel: lag bars
    y_pos = np.arange(len(names))
    ax1.barh(y_pos, lags, color="steelblue", edgecolor="black", linewidth=0.3)
    ax1.set_yticks(y_pos)
    ax1.set_yticklabels(names, fontsize=6)
    ax1.set_xlabel("E→I lag (ms)", fontsize=8)
    ax1.set_title("Inhibition Lag After Excitation", fontsize=9)
    ax1.tick_params(labelsize=6)

    # Right panel: xcorr magnitude bars
    ax2.barh(y_pos, xcorrs, color="coral", edgecolor="black", linewidth=0.3)
    ax2.set_yticks(y_pos)
    ax2.set_yticklabels(names, fontsize=6)
    ax2.set_xlabel("Peak cross-correlation", fontsize=8)
    ax2.set_title("E/I Cross-Correlation Magnitude", fontsize=9)
    ax2.tick_params(labelsize=6)

    fig.suptitle("E/I Lag Cross-Correlation", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "17_ei_lag.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 17_ei_lag.png")


def plot_effective_synaptic_gain(
    rec: RecorderSnapshot, report: DiagnosticsReport, output_dir: str, cfg: PlotConfig,
) -> None:
    """Effective synaptic gain per inter-region tract.

    Horizontal bar chart showing the Pearson correlation between pre- and post-
    region firing rates at the causal lag.  Healthy range is 0.05–0.60.
    """
    gains = report.effective_synaptic_gain
    if not gains:
        return

    # Sort by absolute gain descending
    items = sorted(gains.items(), key=lambda kv: abs(kv[1]), reverse=True)
    labels = [k for k, _ in items]
    values = [v for _, v in items]

    fig_height = max(cfg.timeline_height, len(labels) * 0.3)
    fig, ax = plt.subplots(figsize=(cfg.timeline_width, fig_height))

    y_pos = np.arange(len(labels))
    colors = ["coral" if v > 0.60 else "steelblue" if v >= 0.05 else "gray" for v in values]
    ax.barh(y_pos, values, color=colors, edgecolor="black", linewidth=0.3)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=6)
    ax.set_xlabel("Effective gain (Pearson r at causal lag)", fontsize=8)
    ax.set_title("Effective Synaptic Gain per Tract", fontsize=9)
    ax.axvline(0.05, color="gray", linestyle="--", linewidth=0.6, alpha=0.7)
    ax.axvline(0.60, color="gray", linestyle="--", linewidth=0.6, alpha=0.7)
    ax.tick_params(labelsize=6)

    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "18_effective_synaptic_gain.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 18_effective_synaptic_gain.png")
