"""
Diagnostics plots — all matplotlib visualisations for a DiagnosticsReport.

The public entry point is :func:`plot`, which dispatches to numbered
``_plot_*`` helper functions.  A failure in one plot never prevents the
remaining plots from being saved.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import TYPE_CHECKING, Callable, Dict, List, Optional, Tuple

import matplotlib
import numpy as np
from scipy.signal import spectrogram as sp_spectrogram

from .diagnostics_types import DiagnosticsReport, PopulationStats

if TYPE_CHECKING:
    from .diagnostics_recorder import DiagnosticsRecorder

matplotlib.use("Agg")
import matplotlib.pyplot as plt


@dataclass
class PlotConfig:
    """Scale factors for diagnostic figure sizes.

    Pass a customised instance to :func:`plot` to adapt layout for very
    large brains (>100 populations) or custom display environments.
    """

    col_width: float = 4.0           # inches per subplot column
    row_height: float = 3.0          # inches per subplot row (normal panels)
    compact_row_height: float = 2.5  # inches per subplot row (compact panels)
    trace_row_height: float = 1.8    # inches per time-trace row
    height_per_pop: float = 0.2      # inches per population in vertical listings
    timeline_width: float = 14.0     # width (inches) for full-width time-series plots
    timeline_height: float = 5.0     # height (inches) for fixed-height time-series plots
    max_fig_height: float = 40.0     # hard cap on figure height (inches)


def _get_cmap(name: str, n: int | None = None):
    """Return a Matplotlib colormap using the non-deprecated colormaps registry."""
    cmap = matplotlib.colormaps[name]
    return cmap if n is None else cmap.resampled(n)


# =============================================================================
# PUBLIC ENTRY POINT
# =============================================================================


def plot(rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: Optional[PlotConfig] = None) -> None:
    """Generate and save diagnostic plots to ``output_dir``.

    Requires ``matplotlib``.  Silently skips if it is not installed.
    Each numbered plot is generated by a dedicated ``_plot_*`` function so that
    a failure in one plot never prevents the remaining plots from being saved.
    """
    cfg = cfg or PlotConfig()
    os.makedirs(output_dir, exist_ok=True)
    plot_fns: list[Callable[["DiagnosticsRecorder", DiagnosticsReport, str, PlotConfig], None]] = [
        _plot_firing_rates,
        _plot_population_heatmap,
        _plot_region_spectra,
        _plot_coherence,
        _plot_isi_distributions,
        _plot_homeostatic_gains,
        _plot_stp_efficacy,
        _plot_voltage_traces,
        _plot_raster,
        _plot_ei_phase_portrait,
        _plot_spectrograms,
        _plot_neuromodulator_conc,
        _plot_apical_basal_conductance,
        _plot_voltage_distributions,
        _plot_neuromodulator_conc_by_region,
    ]
    failed_plots: list[str] = []
    for fn in plot_fns:
        try:
            fn(rec, report, output_dir, cfg)
        except Exception as exc:  # noqa: BLE001
            failed_plots.append(f"{fn.__name__}: {exc}")
    print(f"\n  All plots saved to: {output_dir}")
    if failed_plots:
        print(f"  WARNING: {len(failed_plots)} plot(s) failed:")
        for msg in failed_plots:
            print(f"    - {msg}")


# =============================================================================
# COLOUR HELPER
# =============================================================================


def _pop_color(ps: PopulationStats) -> str:
    """Return a hex colour string summarising a population's health."""
    if ps.total_spikes == 0:
        return "#e74c3c"
    if ps.bio_plausibility == "ok":
        return "#2ecc71"
    if ps.bio_plausibility in ("low", "high"):
        return "#f39c12"
    return "#95a5a6"


# =============================================================================
# INDIVIDUAL PLOTS
# =============================================================================


def _plot_firing_rates(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """01 — Horizontal bar chart of mean firing rates per population."""
    fig, ax = plt.subplots(figsize=(cfg.timeline_width, min(cfg.max_fig_height, max(6, rec._n_pops * cfg.height_per_pop))))
    labels, values, colors = [], [], []
    for rn, rs in report.regions.items():
        for pn, ps in rs.populations.items():
            labels.append(f"{rn}:{pn}")
            values.append(ps.mean_fr_hz)
            colors.append(_pop_color(ps))
    y_pos = np.arange(len(labels))
    ax.barh(y_pos, values, color=colors, height=0.8)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=6)
    ax.set_xlabel("Firing rate (Hz)")
    ax.set_title("Population Firing Rates  (green=bio-ok, orange=out-of-range, red=silent)")
    ax.axvline(0, color="k", linewidth=0.5)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "01_firing_rates.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 01_firing_rates.png")


def _plot_population_heatmap(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """02 — Population firing-rate heatmap over time."""
    if report.pop_rate_binned is None:
        return
    pop_keys = rec._pop_keys
    pr = report.pop_rate_binned  # [n_bins, n_pops]
    pr_hz = pr * (1000.0 / rec.config.rate_bin_ms)
    t_axis = np.arange(pr_hz.shape[0]) * rec.config.rate_bin_ms
    fig, ax = plt.subplots(figsize=(cfg.timeline_width + 2, min(cfg.max_fig_height, max(6, rec._n_pops * cfg.height_per_pop * 0.9))))
    vmax = float(np.percentile(pr_hz, 99)) or 1.0
    im = ax.imshow(
        pr_hz.T,
        aspect="auto",
        origin="lower",
        interpolation="none",
        extent=[t_axis[0], t_axis[-1], 0, rec._n_pops],
        cmap="hot",
        vmin=0,
        vmax=vmax,
    )
    ax.set_yticks(np.arange(rec._n_pops) + 0.5)
    ax.set_yticklabels([f"{rn}:{pn}" for rn, pn in pop_keys], fontsize=5)
    ax.set_xlabel("Time (ms)")
    ax.set_title("Population Firing Rate Heatmap (Hz)")
    plt.colorbar(im, ax=ax, label="Firing rate (Hz)")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "02_population_heatmap.png"), dpi=120)
    plt.close(fig)
    print(f"  ✓ 02_population_heatmap.png")


def _plot_region_spectra(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """03 — Per-region normalised band-power bar charts."""
    osc = report.oscillations
    n_plots = len(report.region_keys or [])
    if n_plots == 0:
        return
    ncols = 4
    nrows = (n_plots + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * cfg.col_width, nrows * cfg.compact_row_height))
    axes = np.array(axes).flatten()
    colors_bar = ["#3498db", "#2ecc71", "#f39c12", "#e74c3c", "#9b59b6"]
    for ax_i, rn in enumerate(report.region_keys or []):
        ax = axes[ax_i]
        bp = osc.region_band_power.get(rn, {})
        bands = list(bp.keys())
        powers = [bp[b] for b in bands]
        ax.bar(bands, powers, color=colors_bar[: len(bands)])
        ax.set_title(rn, fontsize=7, pad=2)
        ax.set_ylim(0, 1)
        ax.tick_params(labelsize=6)
        dom_freq = osc.region_dominant_freq.get(rn, 0.0)
        if dom_freq > 0:
            ax.text(0.98, 0.95, f"{dom_freq:.1f} Hz", ha="right", va="top",
                    transform=ax.transAxes, fontsize=7)
    for ax_i in range(n_plots, len(axes)):
        axes[ax_i].set_visible(False)
    fig.suptitle("Per-Region Power Spectra", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "03_region_spectra.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 03_region_spectra.png")


def _plot_coherence(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """04 / 04b / 04c — Cross-regional coherence matrices (theta, beta, gamma)."""
    osc = report.oscillations
    n_r = len(osc.region_order)
    for band_label, coh_mat, fname in [
        ("Theta (4–8 Hz)",   osc.coherence_theta, "04_coherence_theta.png"),
        ("Beta (13–30 Hz)",  osc.coherence_beta,  "04b_coherence_beta.png"),
        ("Gamma (30–100 Hz)", osc.coherence_gamma, "04c_coherence_gamma.png"),
    ]:
        fig, ax = plt.subplots(figsize=(max(8, n_r * 0.5), min(cfg.max_fig_height, max(6, n_r * 0.5))))
        cmap = plt.cm.YlOrRd.copy()  # type: ignore[attr-defined]
        cmap.set_bad(color="lightgrey")  # NaN = unsampled pair → grey
        im = ax.imshow(coh_mat, vmin=0, vmax=1, cmap=cmap, aspect="equal")
        ax.set_xticks(np.arange(n_r))
        ax.set_xticklabels(osc.region_order, rotation=90, fontsize=6)
        ax.set_yticks(np.arange(n_r))
        ax.set_yticklabels(osc.region_order, fontsize=6)
        ax.set_title(f"Cross-Regional Coherence — {band_label}")
        plt.colorbar(im, ax=ax, label="Coherence")
        plt.tight_layout()
        fig.savefig(os.path.join(output_dir, fname), dpi=150)
        plt.close(fig)
        print(f"  ✓ {fname}")


def _plot_isi_distributions(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """05 — ISI histograms for a selection of key populations (full mode only)."""
    if rec.config.mode != "full":
        return
    # Rank all populations by total spike count; show the top 12.
    def _spk(k: Tuple[str, str]) -> int:
        try:
            return report.regions[k[0]].populations[k[1]].total_spikes
        except KeyError:
            return 0

    key_pops = sorted(rec._spike_times.keys(), key=_spk, reverse=True)[:12]
    if not key_pops:
        return
    ncols = min(4, len(key_pops))
    nrows = (len(key_pops) + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * cfg.col_width, nrows * cfg.row_height))
    axes = np.array(axes).flatten()
    for ax_i, key in enumerate(key_pops):
        ax = axes[ax_i]
        all_isis: List[float] = []
        for times in rec._spike_times[key]:
            if len(times) >= 2:
                all_isis.extend(np.diff(times))
        if all_isis:
            isis_ms = np.array(all_isis, dtype=np.float32) * rec.dt_ms
            ax.hist(
                isis_ms, bins=50, range=(0, float(np.percentile(isis_ms, 98))),
                color="#3498db", edgecolor="none", density=True
            )
            cv = np.std(isis_ms) / np.mean(isis_ms) if np.mean(isis_ms) > 0 else 0
            ax.set_title(f"{key[0]}:{key[1]}\nCV={cv:.2f}", fontsize=7)
            ax.set_xlabel("ISI (ms)", fontsize=7)
            ax.tick_params(labelsize=6)
    for ax_i in range(len(key_pops), len(axes)):
        axes[ax_i].set_visible(False)
    fig.suptitle("Inter-Spike Interval Distributions", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "05_isi_distributions.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 05_isi_distributions.png")


def _plot_homeostatic_gains(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """06 — Homeostatic gain trajectories over time."""
    hs = report.homeostasis
    if not hs.gain_trajectories or len(hs.gain_sample_times_ms) <= 1:
        return
    t_ms = hs.gain_sample_times_ms
    fig, ax = plt.subplots(figsize=(cfg.timeline_width, cfg.timeline_height))
    cmap = _get_cmap("tab20")
    for i, (key, traj) in enumerate(sorted(hs.gain_trajectories.items())):
        valid = ~np.isnan(traj)
        if valid.sum() < 2:
            continue
        ax.plot(t_ms[valid], traj[valid], linewidth=0.8, alpha=0.7,
                color=cmap(i % 20), label=key)
    ax.axhline(0.3, color="red", linestyle="--", linewidth=1.0, label="Collapse threshold")
    ax.axhline(1.0, color="gray", linestyle=":", linewidth=0.8)
    ax.set_xlabel("Time (ms)")
    ax.set_ylabel("g_L_scale")
    ax.set_title("Homeostatic Gain Trajectories")
    ax.set_ylim(0, 2.1)
    ax.legend(fontsize=5, ncol=3, loc="upper right")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "06_homeostatic_gains.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 06_homeostatic_gains.png")


def _plot_stp_efficacy(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """06b — STP efficacy (x·u) trajectories per synapse over time."""
    hs_stp = report.homeostasis.stp_efficacy_history
    if not hs_stp or len(report.homeostasis.gain_sample_times_ms) <= 1:
        return
    t_ms = report.homeostasis.gain_sample_times_ms
    fig, ax = plt.subplots(figsize=(cfg.timeline_width, cfg.timeline_height))
    cmap_stp = _get_cmap("tab20")
    for i, (key, traj) in enumerate(sorted(hs_stp.items())):
        valid = ~np.isnan(traj)
        if valid.sum() < 2:
            continue
        ax.plot(t_ms[valid], traj[valid], linewidth=0.8, alpha=0.7,
                color=cmap_stp(i % 20), label=key)
    ax.axhline(0.0, color="gray", linestyle=":", linewidth=0.8)
    ax.set_xlabel("Time (ms)")
    ax.set_ylabel("STP efficacy (x·u)")
    ax.set_title("STP Efficacy Trajectories (per synapse)")
    ax.set_ylim(-0.05, 1.05)
    ax.legend(fontsize=5, ncol=3, loc="upper right")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "06b_stp_efficacy.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 06b_stp_efficacy.png")


def _plot_voltage_traces(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """07 — Sample neuron voltage traces for key populations (full mode only)."""
    if rec.config.mode != "full" or report.raw_voltages is None:
        return
    pop_keys = rec._pop_keys

    # Rank populations by total spike count; show the top 6 with voltage data.
    def _spk_v(rn_pn: Tuple[str, str]) -> int:
        try:
            return report.regions[rn_pn[0]].populations[rn_pn[1]].total_spikes
        except KeyError:
            return 0

    sampled: List[Tuple[str, str, int]] = []
    for rn, pn in sorted(pop_keys, key=_spk_v, reverse=True):
        if len(sampled) >= 6:
            break
        idx = rec._pop_index[(rn, pn)]
        if not np.all(np.isnan(report.raw_voltages[:, idx, :])):
            sampled.append((rn, pn, idx))
    if not sampled:
        return
    fig, axes = plt.subplots(len(sampled), 1, figsize=(cfg.timeline_width + 2, min(cfg.max_fig_height, len(sampled) * cfg.trace_row_height)), sharex=True)
    if len(sampled) == 1:
        axes = [axes]
    t_ms = np.arange(report.n_timesteps, dtype=np.float32) * rec.dt_ms
    for ax, (rn, pn, pidx) in zip(axes, sampled):
        v = report.raw_voltages[:, pidx, :]  # [T, sample_size]
        n_valid = int(rec._pop_sizes[pidx])
        n_show = min(8, n_valid, v.shape[1])
        for ni in range(n_show):
            col = _get_cmap("tab10")(ni)
            y = v[:, ni]
            valid_mask = ~np.isnan(y)
            if valid_mask.sum() > 1:
                ax.plot(t_ms[valid_mask], y[valid_mask], linewidth=0.5, alpha=0.7, color=col)
        ax.set_ylabel(f"{pn}\n({rn})", fontsize=6)
        ax.tick_params(labelsize=6)
    axes[-1].set_xlabel("Time (ms)")
    fig.suptitle("Sample Neuron Voltage Traces", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "07_voltage_traces.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 07_voltage_traces.png")


def _plot_raster(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """08 — Spike raster plots for key regions (full mode only)."""
    if rec.config.mode != "full" or not rec._spike_times:
        return
    # Rank regions by total spike count; show the top 6 most active.
    def _region_spikes(rn: str) -> int:
        rs = report.regions.get(rn)
        return sum(ps.total_spikes for ps in rs.populations.values()) if rs else 0

    existing = sorted(rec.brain.regions.keys(), key=_region_spikes, reverse=True)[:6]
    if not existing:
        return
    fig, axes = plt.subplots(
        len(existing), 1,
        figsize=(cfg.timeline_width + 2, min(cfg.max_fig_height, len(existing) * cfg.compact_row_height)),
        sharex=True,
    )
    if len(existing) == 1:
        axes = [axes]
    t_ms_max = report.n_timesteps * rec.dt_ms
    for ax, rn in zip(axes, existing):
        y_offset = 0
        region = rec.brain.regions[rn]
        pop_colors_raster = _get_cmap("tab10")
        for pi, pn in enumerate(region.neuron_populations.keys()):
            key = (rn, pn)
            if key not in rec._spike_times:
                continue
            n_neurons = len(rec._spike_times[key])
            n_show = min(80, n_neurons)
            col = pop_colors_raster(pi % 10)
            for ni in range(n_show):
                times = rec._spike_times[key][ni]
                if times:
                    t_vals = np.array(times, dtype=np.float32) * rec.dt_ms
                    ax.scatter(
                        t_vals, np.full_like(t_vals, y_offset + ni),
                        s=1.0, c=[col], marker="|", linewidths=0.5
                    )
            ax.axhline(y_offset + n_show, color="gray", linewidth=0.3)
            ax.text(
                t_ms_max * 1.002, y_offset + n_show / 2, pn,
                fontsize=6, va="center"
            )
            y_offset += n_show + 5
        ax.set_ylabel(rn, fontsize=8)
        ax.set_xlim(0, t_ms_max)
        ax.tick_params(labelsize=6)
    axes[-1].set_xlabel("Time (ms)")
    fig.suptitle("Spike Rasters (sample neurons)", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "08_raster_plots.png"), dpi=130)
    plt.close(fig)
    print(f"  ✓ 08_raster_plots.png")


def _plot_ei_phase_portrait(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """09 — E/I conductance phase portraits for key populations (full mode only)."""
    if (
        rec.config.mode != "full"
        or rec._g_exc_samples is None
        or rec._g_inh_samples is None
    ):
        return
    if np.all(np.isnan(rec._g_exc_samples)) or np.all(np.isnan(rec._g_inh_samples)):
        return
    pop_keys = rec._pop_keys
    key_ei_pops = ["relay", "ca1", "l23_pyr", "l4_pyr"]
    sampled_ei: List[Tuple[str, str, int]] = []
    for rn, pn in pop_keys:
        if any(t in pn for t in key_ei_pops) and len(sampled_ei) < 6:
            idx = rec._pop_index[(rn, pn)]
            sampled_ei.append((rn, pn, idx))
    if not sampled_ei:
        return
    fig, axes = plt.subplots(
        1, len(sampled_ei),
        figsize=(len(sampled_ei) * cfg.row_height, cfg.row_height),
    )
    if len(sampled_ei) == 1:
        axes = [axes]
    n_cond = rec._cond_sample_step
    for ax, (rn, pn, pidx) in zip(axes, sampled_ei):
        g_e = rec._g_exc_samples[:n_cond, pidx, :].flatten()
        g_i = rec._g_inh_samples[:n_cond, pidx, :].flatten()
        valid = ~(np.isnan(g_e) | np.isnan(g_i))
        if valid.sum() > 5:
            ax.scatter(g_e[valid], g_i[valid], s=2, alpha=0.4, c="#3498db")
        ax.set_xlabel("g_exc", fontsize=7)
        ax.set_ylabel("g_inh", fontsize=7)
        ax.set_title(f"{pn}\n({rn})", fontsize=7)
        ax.tick_params(labelsize=6)
    fig.suptitle("E/I Conductance Phase Portraits", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "09_ei_phase_portrait.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 09_ei_phase_portrait.png")


def _plot_spectrograms(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """10 — Time-frequency spectrograms of population rates per region."""
    n_steps = rec._n_recorded or rec.config.n_timesteps
    if n_steps <= 0 or rec._n_regions <= 0:
        return
    bin_steps = max(1, int(rec.config.rate_bin_ms / rec.dt_ms))
    n_bins = n_steps // bin_steps
    fs_bins = 1000.0 / rec.config.rate_bin_ms

    # Consume the pre-normalised region-rate matrix from the report (avoids
    # recomputing it with different normalisation from rec._region_spike_counts).
    if report.region_rate_binned is not None and report.region_rate_binned.shape == (n_bins, rec._n_regions):
        region_rate_binned = report.region_rate_binned
    else:
        # Fallback: recompute without population-size normalisation.
        region_rate_binned = np.zeros((n_bins, rec._n_regions), dtype=np.float32)
        for b in range(n_bins):
            start, end = b * bin_steps, (b + 1) * bin_steps
            region_rate_binned[b] = rec._region_spike_counts[start:end].sum(axis=0)

    n_col = min(4, rec._n_regions)
    n_row = (rec._n_regions + n_col - 1) // n_col
    fig_sg, axes_sg = plt.subplots(
        n_row, n_col,
        figsize=(n_col * cfg.col_width, n_row * cfg.row_height),
        squeeze=False,
        sharex=True,
    )
    nperseg_sg = min(n_bins, 128)
    for r_idx, rn in enumerate(rec._region_keys):
        ax = axes_sg[r_idx // n_col][r_idx % n_col]
        trace = region_rate_binned[:, r_idx].astype(float)
        if trace.std() > 0 and nperseg_sg >= 8:
            f_sg, t_sg, Sxx = sp_spectrogram(
                trace, fs=fs_bins, nperseg=nperseg_sg,
                noverlap=nperseg_sg // 2, window="hann", scaling="density"
            )
            f_mask = f_sg <= 100.0
            ax.pcolormesh(
                t_sg, f_sg[f_mask], 10 * np.log10(Sxx[f_mask] + 1e-12),
                shading="gouraud", cmap="magma",
            )
        ax.set_title(rn, fontsize=7)
        ax.set_ylabel("Freq (Hz)", fontsize=6)
        ax.tick_params(labelsize=5)
    for r_idx in range(rec._n_regions, n_row * n_col):
        axes_sg[r_idx // n_col][r_idx % n_col].set_visible(False)
    fig_sg.supxlabel("Time (s)", fontsize=8)
    fig_sg.suptitle("Population Rate Spectrograms", fontsize=10)
    plt.tight_layout()
    fig_sg.savefig(os.path.join(output_dir, "10_spectrograms.png"), dpi=130)
    plt.close(fig_sg)
    print(f"  ✓ 10_spectrograms.png")


def _plot_neuromodulator_conc(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """11 — Neuromodulator receptor concentration trajectories over time."""
    if not report.neuromodulator_levels:
        return
    t_ms = report.homeostasis.gain_sample_times_ms
    nm_levels = report.neuromodulator_levels
    n_receptors = len(nm_levels)
    n_col_nm = min(4, n_receptors)
    n_row_nm = (n_receptors + n_col_nm - 1) // n_col_nm
    fig_nm, axes_nm = plt.subplots(
        n_row_nm, n_col_nm,
        figsize=(n_col_nm * cfg.col_width, n_row_nm * cfg.compact_row_height),
        squeeze=False,
        sharex=True,
    )
    for nm_i, (key, traj) in enumerate(sorted(nm_levels.items())):
        ax = axes_nm[nm_i // n_col_nm][nm_i % n_col_nm]
        valid = ~np.isnan(traj)
        if valid.sum() > 1 and len(t_ms) >= valid.sum():
            ax.plot(t_ms[:valid.sum()], traj[valid], linewidth=1.0, color="#9b59b6")
        ax.set_title(key, fontsize=6)
        ax.set_ylabel("Concentration", fontsize=6)
        ax.set_ylim(-0.02, 1.05)
        ax.axhline(0, color="gray", linewidth=0.5, linestyle=":")
        ax.tick_params(labelsize=5)
    for nm_i in range(n_receptors, n_row_nm * n_col_nm):
        axes_nm[nm_i // n_col_nm][nm_i % n_col_nm].set_visible(False)
    fig_nm.supxlabel("Time (ms)", fontsize=8)
    fig_nm.suptitle("Neuromodulator Receptor Concentrations", fontsize=10)
    plt.tight_layout()
    fig_nm.savefig(os.path.join(output_dir, "11_neuromodulator_conc.png"), dpi=150)
    plt.close(fig_nm)
    print(f"  ✓ 11_neuromodulator_conc.png")


def _plot_apical_basal_conductance(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """12 — Apical vs. basal AMPA conductance per population (full mode, TwoCompartmentLIF only)."""
    if (
        rec.config.mode != "full"
        or rec._g_apical_samples is None
        or rec._g_exc_samples is None
        or rec._cond_sample_step == 0
    ):
        return
    n_cond = rec._cond_sample_step

    labels: List[str] = []
    basal_means: List[float] = []
    apical_means: List[float] = []
    for pidx, (rn, pn) in enumerate(rec._pop_keys):
        apical_slab = rec._g_apical_samples[:n_cond, pidx, :]
        apical_mean = float(np.nanmean(apical_slab))
        if np.isnan(apical_mean):
            continue
        basal_slab = rec._g_exc_samples[:n_cond, pidx, :]
        basal_mean = float(np.nanmean(basal_slab))
        if np.isnan(basal_mean):
            basal_mean = 0.0
        labels.append(f"{pn}\n({rn})")
        basal_means.append(basal_mean)
        apical_means.append(apical_mean)

    if not labels:
        return

    n = len(labels)
    y = np.arange(n)
    bar_h = 0.35
    fig, ax = plt.subplots(figsize=(10, min(cfg.max_fig_height, max(4, n * 0.55))))
    ax.barh(y - bar_h / 2, basal_means, bar_h, label="Basal (g_exc AMPA)", color="#3498db", alpha=0.85)
    ax.barh(y + bar_h / 2, apical_means, bar_h, label="Apical (g_exc_apical)", color="#e67e22", alpha=0.85)
    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=7)
    ax.set_xlabel("Mean conductance")
    ax.set_title("Apical vs. Basal AMPA Conductance per Population")
    ax.legend(fontsize=8)
    ax.axvline(0, color="black", linewidth=0.5)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "12_apical_basal_conductance.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 12_apical_basal_conductance.png")


def _plot_voltage_distributions(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """13 — Per-population voltage distributions as violin plots (full mode only)."""
    if rec.config.mode != "full" or report.raw_voltages is None:
        return

    pops_with_data: List[Tuple[str, str, int]] = []
    for pidx, (rn, pn) in enumerate(rec._pop_keys):
        if not np.all(np.isnan(report.raw_voltages[:, pidx, :])):
            pops_with_data.append((rn, pn, pidx))

    if not pops_with_data:
        return

    n = len(pops_with_data)
    n_col = min(4, n)
    n_row = (n + n_col - 1) // n_col
    fig, axes = plt.subplots(n_row, n_col, figsize=(n_col * cfg.col_width, n_row * cfg.row_height), squeeze=False)

    for i, (rn, pn, pidx) in enumerate(pops_with_data):
        ax = axes[i // n_col][i % n_col]
        v_flat = report.raw_voltages[:, pidx, :].flatten()
        v_flat = v_flat[~np.isnan(v_flat)]
        if len(v_flat) < 10:
            ax.set_visible(False)
            continue
        vp = ax.violinplot(v_flat, showmedians=True, showextrema=False)
        for body in vp.get("bodies", []):
            body.set_facecolor("#3498db")
            body.set_alpha(0.7)
        rs = report.regions.get(rn)
        pop_stats = rs.populations.get(pn) if rs else None
        bc = (
            pop_stats.voltage_bimodality
            if pop_stats is not None and not np.isnan(pop_stats.voltage_bimodality)
            else None
        )
        subtitle = f"({rn})"
        if bc is not None:
            subtitle += f"  BC={bc:.3f}"
        ax.set_title(f"{pn}\n{subtitle}", fontsize=6)
        ax.set_xticks([])
        ax.set_ylabel("Voltage (mV)", fontsize=6)
        ax.tick_params(labelsize=6)

    for i in range(len(pops_with_data), n_row * n_col):
        axes[i // n_col][i % n_col].set_visible(False)

    fig.suptitle("Population Voltage Distributions", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "13_voltage_distributions.png"), dpi=130)
    plt.close(fig)
    print(f"  ✓ 13_voltage_distributions.png")


def _plot_neuromodulator_conc_by_region(
    rec: "DiagnosticsRecorder", report: DiagnosticsReport, output_dir: str, cfg: PlotConfig
) -> None:
    """14 — Neuromodulator receptor concentrations grouped by brain region."""
    if not report.neuromodulator_levels:
        return
    t_ms = report.homeostasis.gain_sample_times_ms
    nm_levels = report.neuromodulator_levels  # keys: "{region}/{mod_name}"

    by_region: Dict[str, List[Tuple[str, np.ndarray]]] = {}
    for key in sorted(nm_levels.keys()):
        rn, mod_name = key.split("/", 1)
        if rn not in by_region:
            by_region[rn] = []
        by_region[rn].append((mod_name, nm_levels[key]))

    if not by_region:
        return

    n_regions = len(by_region)
    n_col = min(3, n_regions)
    n_row = (n_regions + n_col - 1) // n_col
    fig, axes = plt.subplots(
        n_row, n_col,
        figsize=(n_col * (cfg.col_width + 1.0), n_row * cfg.row_height),
        squeeze=False,
        sharex=True,
    )
    colors = [_get_cmap("tab10")(i) for i in range(10)]

    for r_i, (rn, mod_list) in enumerate(sorted(by_region.items())):
        ax = axes[r_i // n_col][r_i % n_col]
        for m_i, (mod_name, traj) in enumerate(mod_list):
            valid = ~np.isnan(traj)
            if valid.sum() > 1 and len(t_ms) >= valid.sum():
                ax.plot(
                    t_ms[: valid.sum()], traj[valid],
                    linewidth=1.2, color=colors[m_i % 10], label=mod_name,
                )
        ax.set_title(rn, fontsize=8)
        ax.set_ylabel("Concentration", fontsize=6)
        ax.set_ylim(-0.02, 1.05)
        ax.axhline(0, color="gray", linewidth=0.5, linestyle=":")
        ax.legend(fontsize=5, loc="upper right")
        ax.tick_params(labelsize=5)

    for r_i in range(n_regions, n_row * n_col):
        axes[r_i // n_col][r_i % n_col].set_visible(False)

    fig.supxlabel("Time (ms)", fontsize=8)
    fig.suptitle("Neuromodulator Concentrations by Region", fontsize=10)
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "14_neuromodulator_conc_by_region.png"), dpi=150)
    plt.close(fig)
    print(f"  ✓ 14_neuromodulator_conc_by_region.png")
